[#ftl]
[@b.head/]
[@b.toolbar title="编辑成果获奖情况"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(rdAchievementAward) theme="list"]
    [@b.textfield name="rdAchievementAward.awardYear" label="获奖年度" value=rdAchievementAward.awardYear! required="true" maxlength="4"/]
    [@b.date name="rdAchievementAward.awardOn" label="获奖年月" value=rdAchievementAward.awardOn! required="false" format="yyyy-MM"/]
    [@b.textfield name="rdAchievementAward.name" label="奖项名称" value=rdAchievementAward.name! required="true" maxlength="200"/]
    [@b.select name="rdAchievementAward.grade.id" label="获奖级别" value=rdAchievementAward.grade! required="true"  items=grades  empty="..."/]
    [@b.select name="rdAchievementAward.level.id" label="获奖等级" value=rdAchievementAward.level! required="true"  items=levels  empty="..."/]
    [@b.textfield name="rdAchievementAward.awardBy" label="授奖单位" value=rdAchievementAward.awardBy! required="true" maxlength="200"/]
    [@b.formfoot]
      <input type="hidden" name="rdAchievementAward.achievement.id" value="${Parameters['rdAchievementAward.achievement.id']}"/>
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[#list 1..10 as i]<br>[/#list]
[@b.foot/]
