[#ftl]
[@b.head/]
[@b.toolbar title="修改项目类别"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(rdProjectCategory) theme="list"]
    [@b.textfield name="rdProjectCategory.code" label="代码" value=rdProjectCategory.code! required="true" maxlength="20"/]
    [@b.textfield name="rdProjectCategory.name" label="名称" value="${rdProjectCategory.name!}" required="true" maxlength="20"/]
    [@b.textfield name="rdProjectCategory.enName" label="英文名称" value="${rdProjectCategory.enName!}" maxlength="100"/]
    [@b.radios name="rdProjectCategory.forCourse" label="使用范围" items={"1":"课程项目","0":"教改项目"} value=rdProjectCategory.forCourse/]
    [@b.startend label="有效期限"
      name="rdProjectCategory.beginOn,rdProjectCategory.endOn" required="true,false"
      start=rdProjectCategory.beginOn end=rdProjectCategory.endOn format="date"/]
    [@b.textfield name="rdProjectCategory.remark" label="备注" value="${rdProjectCategory.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
