[#ftl]
[@b.head/]
[@b.toolbar title="修改成果类型"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(rdAchievementType) theme="list"]
    [@b.textfield name="rdAchievementType.code" label="代码" value="${rdAchievementType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="rdAchievementType.name" label="名称" value="${rdAchievementType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="rdAchievementType.enName" label="英文名称" value="${rdAchievementType.enName!}" maxlength="100"/]
    [@b.startend label="有效期限"
      name="rdAchievementType.beginOn,rdAchievementType.endOn" required="true,false"
      start=rdAchievementType.beginOn end=rdAchievementType.endOn format="date"/]
    [@b.textfield name="rdAchievementType.remark" label="备注" value="${rdAchievementType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
