[#ftl]
[@b.head/]
[@b.toolbar title="修改项目类别"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(rdProjectLevel) theme="list"]
    [@b.textfield name="rdProjectLevel.code" label="代码" value="${rdProjectLevel.name!}" required="true" maxlength="20"/]
    [@b.textfield name="rdProjectLevel.name" label="名称" value="${rdProjectLevel.name!}" required="true" maxlength="20"/]
    [@b.textfield name="rdProjectLevel.enName" label="英文名称" value="${rdProjectLevel.enName!}" maxlength="100"/]
    [@b.startend label="有效期限"
      name="rdProjectLevel.beginOn,rdProjectLevel.endOn" required="true,false"
      start=rdProjectLevel.beginOn end=rdProjectLevel.endOn format="date"/]
    [@b.textfield name="rdProjectLevel.remark" label="备注" value="${rdProjectLevel.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
