[#ftl]
[@b.head/]
[@b.toolbar title="编辑教材获奖情况"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(textbookAward) theme="list"]
    [@b.date name="textbookAward.awardOn" label="获奖年月" value=textbookAward.awardOn! required="false" format="yyyy-MM"/]
    [@b.textfield name="textbookAward.name" label="奖项名称" value=textbookAward.name! required="true" maxlength="200"/]
    [@b.select name="textbookAward.level.id" label="获奖级别" value=textbookAward.level! required="true"  items=levels  empty="..."/]
    [@b.select name="textbookAward.grade.id" label="获奖等级" value=textbookAward.grade! required="false"  items=grades  empty="..."/]
    [@b.formfoot]
      <input type="hidden" name="textbookAward.achievement.id" value="${Parameters['textbookAward.achievement.id']}"/>
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[#list 1..10 as i]<br>[/#list]
[@b.foot/]
